# Generated by Django 2.1.2 on 2020-10-01 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('userid', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=75)),
                ('self_introduction', models.CharField(max_length=500)),
                ('header', models.ImageField(upload_to='imgs/')),
                ('icon', models.ImageField(upload_to='imgs/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('detail', models.CharField(max_length=500)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('origin', models.ImageField(upload_to='photos/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('userid', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('self_introduction', models.CharField(max_length=500)),
                ('header', models.ImageField(upload_to='imgs/')),
                ('icon', models.ImageField(upload_to='imgs/')),
            ],
        ),
    ]
